# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list
    silent: true

  install-uv:
    desc: Install uv package manager
    cmds:
      - cmd: curl -LsSf https://astral.sh/uv/install.sh | sh
        platforms: [darwin, linux]
      - cmd: powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"
        platforms: [windows]
    status:
      - command -v uv

  sync:
    desc: Install all project dependencies (including dev)
    deps: [install-uv]
    cmds:
      - uv sync --all-groups

  setup:
    desc: Set up the development environment
    deps: [sync, pre-commit:install]
    cmds:
      - echo "Development environment ready!"

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install
    status:
      - test -f .git/hooks/pre-commit

  pre-commit:run:
    desc: Run pre-commit on all files
    cmds:
      - uv run pre-commit run --all-files

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format .

  lint:
    desc: Lint code with ruff
    cmds:
      - uv run ruff check . --fix

  typecheck:
    desc: Type check with mypy
    cmds:
      - uv run mypy src/

  test:
    desc: Run tests with pytest
    cmds:
      - uv run pytest tests/ -v --cov=src --cov-report=term-missing

  ci:
    desc: Run CI tasks
    deps: [lint, typecheck, test, format, pre-commit:run]
